services:
  blog:
    build: .
    ports:
      - "5001:5001"
      - "9230:9230"
    command: npm run dev
    develop:
      watch:
        - action : rebuild
          path : ./package.json

        - action : sync+restart
          path : .
          target : /usr/src/app
          exec : 
            command : npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    hostname: mongo-blog
    command: mongod --quiet --logpath /dev/null
    env_file: ".env"
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d/