const NOT_FOUND = 404;
const UNAUTHORIZED = 403;
const ACCESS_DENIED = 401;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const SUCCESS_OK = 200;
const SUCCESS_CREATED = 201;

module.exports = {
    NOT_FOUND,
    UNAUTHORIZED,
    ACCESS_DENIED,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    SUCCESS_OK,
    SUCCESS_CREATED
}